//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.GetProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private int SupplierIDField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityPerUnitField;
        
        private double UnitPriceField;
        
        private int UnitsInStockField;
        
        private int UnitsOnOrderField;
        
        private int ReorderLevelField;
        
        private bool DiscontinuedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityPerUnitField, value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int UnitsInStock {
            get {
                return this.UnitsInStockField;
            }
            set {
                if ((this.UnitsInStockField.Equals(value) != true)) {
                    this.UnitsInStockField = value;
                    this.RaisePropertyChanged("UnitsInStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int UnitsOnOrder {
            get {
                return this.UnitsOnOrderField;
            }
            set {
                if ((this.UnitsOnOrderField.Equals(value) != true)) {
                    this.UnitsOnOrderField = value;
                    this.RaisePropertyChanged("UnitsOnOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ReorderLevel {
            get {
                return this.ReorderLevelField;
            }
            set {
                if ((this.ReorderLevelField.Equals(value) != true)) {
                    this.ReorderLevelField = value;
                    this.RaisePropertyChanged("ReorderLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Discontinued {
            get {
                return this.DiscontinuedField;
            }
            set {
                if ((this.DiscontinuedField.Equals(value) != true)) {
                    this.DiscontinuedField = value;
                    this.RaisePropertyChanged("Discontinued");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetProductService.testSoap")]
    public interface testSoap {
        
        // CODEGEN: Generating message contract since element name GetALLProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetALLProduct", ReplyAction="*")]
        WebApplication1.GetProductService.GetALLProductResponse GetALLProduct(WebApplication1.GetProductService.GetALLProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetALLProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.GetProductService.GetALLProductResponse> GetALLProductAsync(WebApplication1.GetProductService.GetALLProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name GetCalculationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculation", ReplyAction="*")]
        WebApplication1.GetProductService.GetCalculationResponse GetCalculation(WebApplication1.GetProductService.GetCalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.GetProductService.GetCalculationResponse> GetCalculationAsync(WebApplication1.GetProductService.GetCalculationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetALLProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetALLProduct", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.GetProductService.GetALLProductRequestBody Body;
        
        public GetALLProductRequest() {
        }
        
        public GetALLProductRequest(WebApplication1.GetProductService.GetALLProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetALLProductRequestBody {
        
        public GetALLProductRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetALLProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetALLProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.GetProductService.GetALLProductResponseBody Body;
        
        public GetALLProductResponse() {
        }
        
        public GetALLProductResponse(WebApplication1.GetProductService.GetALLProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetALLProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.GetProductService.Product[] GetALLProductResult;
        
        public GetALLProductResponseBody() {
        }
        
        public GetALLProductResponseBody(WebApplication1.GetProductService.Product[] GetALLProductResult) {
            this.GetALLProductResult = GetALLProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculation", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.GetProductService.GetCalculationRequestBody Body;
        
        public GetCalculationRequest() {
        }
        
        public GetCalculationRequest(WebApplication1.GetProductService.GetCalculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationRequestBody {
        
        public GetCalculationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.GetProductService.GetCalculationResponseBody Body;
        
        public GetCalculationResponse() {
        }
        
        public GetCalculationResponse(WebApplication1.GetProductService.GetCalculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCalculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.GetProductService.ArrayOfString GetCalculationResult;
        
        public GetCalculationResponseBody() {
        }
        
        public GetCalculationResponseBody(WebApplication1.GetProductService.ArrayOfString GetCalculationResult) {
            this.GetCalculationResult = GetCalculationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface testSoapChannel : WebApplication1.GetProductService.testSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class testSoapClient : System.ServiceModel.ClientBase<WebApplication1.GetProductService.testSoap>, WebApplication1.GetProductService.testSoap {
        
        public testSoapClient() {
        }
        
        public testSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public testSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public testSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public testSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.GetProductService.GetALLProductResponse WebApplication1.GetProductService.testSoap.GetALLProduct(WebApplication1.GetProductService.GetALLProductRequest request) {
            return base.Channel.GetALLProduct(request);
        }
        
        public WebApplication1.GetProductService.Product[] GetALLProduct() {
            WebApplication1.GetProductService.GetALLProductRequest inValue = new WebApplication1.GetProductService.GetALLProductRequest();
            inValue.Body = new WebApplication1.GetProductService.GetALLProductRequestBody();
            WebApplication1.GetProductService.GetALLProductResponse retVal = ((WebApplication1.GetProductService.testSoap)(this)).GetALLProduct(inValue);
            return retVal.Body.GetALLProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.GetProductService.GetALLProductResponse> WebApplication1.GetProductService.testSoap.GetALLProductAsync(WebApplication1.GetProductService.GetALLProductRequest request) {
            return base.Channel.GetALLProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.GetProductService.GetALLProductResponse> GetALLProductAsync() {
            WebApplication1.GetProductService.GetALLProductRequest inValue = new WebApplication1.GetProductService.GetALLProductRequest();
            inValue.Body = new WebApplication1.GetProductService.GetALLProductRequestBody();
            return ((WebApplication1.GetProductService.testSoap)(this)).GetALLProductAsync(inValue);
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.GetProductService.GetCalculationResponse WebApplication1.GetProductService.testSoap.GetCalculation(WebApplication1.GetProductService.GetCalculationRequest request) {
            return base.Channel.GetCalculation(request);
        }
        
        public WebApplication1.GetProductService.ArrayOfString GetCalculation() {
            WebApplication1.GetProductService.GetCalculationRequest inValue = new WebApplication1.GetProductService.GetCalculationRequest();
            inValue.Body = new WebApplication1.GetProductService.GetCalculationRequestBody();
            WebApplication1.GetProductService.GetCalculationResponse retVal = ((WebApplication1.GetProductService.testSoap)(this)).GetCalculation(inValue);
            return retVal.Body.GetCalculationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.GetProductService.GetCalculationResponse> WebApplication1.GetProductService.testSoap.GetCalculationAsync(WebApplication1.GetProductService.GetCalculationRequest request) {
            return base.Channel.GetCalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.GetProductService.GetCalculationResponse> GetCalculationAsync() {
            WebApplication1.GetProductService.GetCalculationRequest inValue = new WebApplication1.GetProductService.GetCalculationRequest();
            inValue.Body = new WebApplication1.GetProductService.GetCalculationRequestBody();
            return ((WebApplication1.GetProductService.testSoap)(this)).GetCalculationAsync(inValue);
        }
    }
}
